baseURL = "https://hyegyeongseo.github.io/"
languageCode = "ko"
title = "기록 블로그"
theme = "PaperMod"
paginate = 10
timezone = "Asia/Seoul"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  description = "트러블슈팅 기록"
  author = "hyegyeongseo"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = true

  [params.homeInfoParams]
    Title = "기록 블로그"
    Content = "시행착오를 기록합니다"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/hyegyeongseo"

[menus]
  [[menus.main]]
    name = "Tags"
    url = "/tags/"
    weight = 1

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    codeFences = true
